var countryCodesAndNames = [
  {
    CCA2: "AD",
    Name: "Andorra",
    CCA3: "AND",
    Nationality: "Andorran",
  },
  {
    CCA2: "AE",
    Name: "UAE",
    CCA3: "ARE",
    Nationality: "Emirati",
  },
  {
    CCA2: "AF",
    Name: "Afghanistan",
    CCA3: "AFG",
    Nationality: "Afghan",
  },
  {
    CCA2: "AG",
    Name: "Antigua and Barbuda",
    CCA3: "ATG",
    Nationality: "Antiguan, Barbudan",
  },
  {
    CCA2: "AI",
    Name: "Anguilla",
    CCA3: "AIA",
    Nationality: "Anguillian",
  },
  {
    CCA2: "AL",
    Name: "Albania",
    CCA3: "ALB",
    Nationality: "Albanian",
  },
  {
    CCA2: "AM",
    Name: "Armenia",
    CCA3: "ARM",
    Nationality: "Armenian",
  },
  {
    CCA2: "AO",
    Name: "Angola",
    CCA3: "AGO",
    Nationality: "Angolan",
  },
  {
    CCA2: "AR",
    Name: "Argentina",
    CCA3: "ARG",
    Nationality: "Argentine",
  },
  {
    CCA2: "AT",
    Name: "Austria",
    CCA3: "AUT",
    Nationality: "Austrian",
  },
  {
    CCA2: "AU",
    Name: "Australia",
    CCA3: "AUS",
    Nationality: "Australian",
  },
  {
    CCA2: "AW",
    Name: "Aruba",
    CCA3: "ABW",
    Nationality: "Aruban",
  },
  {
    CCA2: "AZ",
    Name: "Azerbaijan",
    CCA3: "AZE",
    Nationality: "Azerbaijani",
  },
  {
    CCA2: "BA",
    Name: "Bosnia and Herzegovina",
    CCA3: "BIH",
    Nationality: "Bosnian, Herzegovinian",
  },
  {
    CCA2: "BB",
    Name: "Barbados",
    CCA3: "BRB",
    Nationality: "Barbadian",
  },
  {
    CCA2: "BD",
    Name: "Bangladesh",
    CCA3: "BGD",
    Nationality: "Bangladeshi",
  },
  {
    CCA2: "BE",
    Name: "Belgium",
    CCA3: "BEL",
    Nationality: "Belgian",
  },
  {
    CCA2: "BF",
    Name: "Burkina Faso",
    CCA3: "BFA",
    Nationality: "Burkinabe",
  },
  {
    CCA2: "BG",
    Name: "Bulgaria",
    CCA3: "BGR",
    Nationality: "Bulgarian",
  },
  {
    CCA2: "BH",
    Name: "Bahrain",
    CCA3: "BHR",
    Nationality: "Bahraini",
  },
  {
    CCA2: "BI",
    Name: "Burundi",
    CCA3: "BDI",
    Nationality: "Burundian",
  },
  {
    CCA2: "BJ",
    Name: "Benin",
    CCA3: "BEN",
    Nationality: "Beninese",
  },
  {
    CCA2: "BL",
    Name: "Saint Barthélemy",
    CCA3: "BLM",
    Nationality: "Saint Barthélemy Islander",
  },
  {
    CCA2: "BM",
    Name: "Bermuda",
    CCA3: "BMU",
    Nationality: "Bermudian",
  },
  {
    CCA2: "BN",
    Name: "Brunei",
    CCA3: "BRN",
    Nationality: "Bruneian",
  },
  {
    CCA2: "BO",
    Name: "Bolivia",
    CCA3: "BOL",
    Nationality: "Bolivian",
  },
  {
    CCA2: "BR",
    Name: "Brazil",
    CCA3: "BRA",
    Nationality: "Brazilian",
  },
  {
    CCA2: "BS",
    Name: "Bahamas",
    CCA3: "BHS",
    Nationality: "Bahamian",
  },
  {
    CCA2: "BT",
    Name: "Bhutan",
    CCA3: "BTN",
    Nationality: "Bhutanese",
  },
  {
    CCA2: "BW",
    Name: "Botswana",
    CCA3: "BWA",
    Nationality: "Motswana",
  },
  {
    CCA2: "BY",
    Name: "Belarus",
    CCA3: "BLR",
    Nationality: "Belarusian",
  },
  {
    CCA2: "BZ",
    Name: "Belize",
    CCA3: "BLZ",
    Nationality: "Belizean",
  },
  {
    CCA2: "CA",
    Name: "Canada",
    CCA3: "CAN",
    Nationality: "Canadian",
  },
  {
    CCA2: "CC",
    Name: "Cocos [Keeling] Islands",
    CCA3: "CCK",
    Nationality: "Cocos Islander",
  },
  {
    CCA2: "CD",
    Name: "Congo - Kinshasa",
    CCA3: "COD",
    Nationality: "Congolese",
  },
  {
    CCA2: "CF",
    Name: "Central African Republic",
    CCA3: "CAF",
    Nationality: "Central African",
  },
  {
    CCA2: "CG",
    Name: "Congo - Brazzaville",
    CCA3: "COG",
    Nationality: "Congolese",
  },
  {
    CCA2: "CH",
    Name: "Switzerland",
    CCA3: "CHE",
    Nationality: "Swiss",
  },
  {
    CCA2: "CI",
    Name: "Côte d’Ivoire",
    CCA3: "CIV",
    Nationality: "Ivorian",
  },
  {
    CCA2: "CK",
    Name: "Cook Islands",
    CCA3: "COK",
    Nationality: "Cook Islander",
  },
  {
    CCA2: "CL",
    Name: "Chile",
    CCA3: "CHL",
    Nationality: "Chilean",
  },
  {
    CCA2: "CM",
    Name: "Cameroon",
    CCA3: "CMR",
    Nationality: "Cameroonian",
  },
  {
    CCA2: "CN",
    Name: "China",
    CCA3: "CHN",
    Nationality: "Chinese",
  },
  {
    CCA2: "CO",
    Name: "Colombia",
    CCA3: "COL",
    Nationality: "Colombian",
  },
  {
    CCA2: "CR",
    Name: "Costa Rica",
    CCA3: "CRI",
    Nationality: "Costa Rican",
  },
  {
    CCA2: "CS",
    Name: "Serbia and Montenegro",
    CCA3: "SCG",
    Nationality: "Montenegrins, Serbs",
  },
  {
    CCA2: "CU",
    Name: "Cuba",
    CCA3: "CUB",
    Nationality: "Cuban",
  },
  {
    CCA2: "CV",
    Name: "Cape Verde",
    CCA3: "CPV",
    Nationality: "Cape Verdian",
  },
  {
    CCA2: "CX",
    Name: "Christmas Island",
    CCA3: "CXR",
    Nationality: "Christmas Island",
  },
  {
    CCA2: "CY",
    Name: "Cyprus",
    CCA3: "CYP",
    Nationality: "Cypriot",
  },
  {
    CCA2: "CZ",
    Name: "Czech Republic",
    CCA3: "CZE",
    Nationality: "Czech",
  },
  {
    CCA2: "DE",
    Name: "Germany",
    CCA3: "DEU",
    Nationality: "German",
  },
  {
    CCA2: "DJ",
    Name: "Djibouti",
    CCA3: "DJI",
    Nationality: "Djibouti",
  },
  {
    CCA2: "DK",
    Name: "Denmark",
    CCA3: "DNK",
    Nationality: "Danish",
  },
  {
    CCA2: "DM",
    Name: "Dominica",
    CCA3: "DMA",
    Nationality: "Dominican",
  },
  {
    CCA2: "DO",
    Name: "Dominican Republic",
    CCA3: "DOM",
    Nationality: "Dominican",
  },
  {
    CCA2: "DZ",
    Name: "Algeria",
    CCA3: "DZA",
    Nationality: "Algerian",
  },
  {
    CCA2: "EC",
    Name: "Ecuador",
    CCA3: "ECU",
    Nationality: "Ecuadorean",
  },
  {
    CCA2: "EE",
    Name: "Estonia",
    CCA3: "EST",
    Nationality: "Estonian",
  },
  {
    CCA2: "EG",
    Name: "Egypt",
    CCA3: "EGY",
    Nationality: "Egyptian",
  },
  {
    CCA2: "EH",
    Name: "Western Sahara",
    CCA3: "ESH",
    Nationality: "Sahrawi",
  },
  {
    CCA2: "ER",
    Name: "Eritrea",
    CCA3: "ERI",
    Nationality: "Eritrean",
  },
  {
    CCA2: "ES",
    Name: "Spain",
    CCA3: "ESP",
    Nationality: "Spanish",
  },
  {
    CCA2: "ET",
    Name: "Ethiopia",
    CCA3: "ETH",
    Nationality: "Ethiopian",
  },
  {
    CCA2: "FI",
    Name: "Finland",
    CCA3: "FIN",
    Nationality: "Finnish",
  },
  {
    CCA2: "FJ",
    Name: "Fiji",
    CCA3: "FJI",
    Nationality: "Fijian",
  },
  {
    CCA2: "FK",
    Name: "Falkland Islands",
    CCA3: "FLK",
    Nationality: "Falkland Islander",
  },
  {
    CCA2: "FM",
    Name: "Micronesia",
    CCA3: "FSM",
    Nationality: "Micronesian",
  },
  {
    CCA2: "FO",
    Name: "Faroe Islands",
    CCA3: "FRO",
    Nationality: "Faroese",
  },
  {
    CCA2: "FR",
    Name: "France",
    CCA3: "FRA",
    Nationality: "French",
  },
  {
    CCA2: "GA",
    Name: "Gabon",
    CCA3: "GAB",
    Nationality: "Gabonese",
  },
  {
    CCA2: "GB",
    Name: "UK",
    CCA3: "GBR",
    Nationality: "British",
  },
  {
    CCA2: "GD",
    Name: "Grenada",
    CCA3: "GRD",
    Nationality: "Grenadian",
  },
  {
    CCA2: "GE",
    Name: "Georgia",
    CCA3: "GEO",
    Nationality: "Georgian",
  },
  {
    CCA2: "GG",
    Name: "Guernsey",
    CCA3: "GGY",
    Nationality: "Channel Islander",
  },
  {
    CCA2: "GH",
    Name: "Ghana",
    CCA3: "GHA",
    Nationality: "Ghanaian",
  },
  {
    CCA2: "GI",
    Name: "Gibraltar",
    CCA3: "GIB",
    Nationality: "Gibraltar",
  },
  {
    CCA2: "GL",
    Name: "Greenland",
    CCA3: "GRL",
    Nationality: "Greenlandic",
  },
  {
    CCA2: "GM",
    Name: "Gambia",
    CCA3: "GMB",
    Nationality: "Gambian",
  },
  {
    CCA2: "GN",
    Name: "Guinea",
    CCA3: "GIN",
    Nationality: "Guinean",
  },
  {
    CCA2: "GP",
    Name: "Guadeloupe",
    CCA3: "GLP",
    Nationality: "Guadeloupian",
  },
  {
    CCA2: "GQ",
    Name: "Equatorial Guinea",
    CCA3: "GNQ",
    Nationality: "Equatorial Guinean",
  },
  {
    CCA2: "GR",
    Name: "Greece",
    CCA3: "GRC",
    Nationality: "Greek",
  },
  {
    CCA2: "GS",
    Name: "South Georgia and the South Sandwich Islands",
    CCA3: "SGS",
    Nationality: "South Georgia and the South Sandwich Islander",
  },
  {
    CCA2: "GT",
    Name: "Guatemala",
    CCA3: "GTM",
    Nationality: "Guatemalan",
  },
  {
    CCA2: "GU",
    Name: "Guam",
    CCA3: "GUM",
    Nationality: "Guamanian",
  },
  {
    CCA2: "GW",
    Name: "Guinea-Bissau",
    CCA3: "GNB",
    Nationality: "Guinea-Bissauan",
  },
  {
    CCA2: "GY",
    Name: "Guyana",
    CCA3: "GUY",
    Nationality: "Guyanese",
  },
  {
    CCA2: "HK",
    Name: "Hong Kong SAR China",
    CCA3: "HKG",
    Nationality: "Chinese",
  },
  {
    CCA2: "HM",
    Name: "Heard Island and McDonald Islands",
    CCA3: "HMD",
    Nationality: "Heard and McDonald Islander",
  },
  {
    CCA2: "HN",
    Name: "Honduras",
    CCA3: "HND",
    Nationality: "Honduran",
  },
  {
    CCA2: "HR",
    Name: "Croatia",
    CCA3: "HRV",
    Nationality: "Croatian",
  },
  {
    CCA2: "HT",
    Name: "Haiti",
    CCA3: "HTI",
    Nationality: "Haitian",
  },
  {
    CCA2: "HU",
    Name: "Hungary",
    CCA3: "HUN",
    Nationality: "Hungarian",
  },
  {
    CCA2: "ID",
    Name: "Indonesia",
    CCA3: "IDN",
    Nationality: "Indonesian",
  },
  {
    CCA2: "IE",
    Name: "Ireland",
    CCA3: "IRL",
    Nationality: "Irish",
  },
  {
    CCA2: "IL",
    Name: "Israel",
    CCA3: "ISR",
    Nationality: "Israeli",
  },
  {
    CCA2: "IM",
    Name: "Isle of Man",
    CCA3: "IMN",
    Nationality: "Manx",
  },
  {
    CCA2: "IN",
    Name: "India",
    CCA3: "IND",
    Nationality: "Indian",
  },
  {
    CCA2: "IQ",
    Name: "Iraq",
    CCA3: "IRQ",
    Nationality: "Iraqi",
  },
  {
    CCA2: "IR",
    Name: "Iran",
    CCA3: "IRN",
    Nationality: "Iranian",
  },
  {
    CCA2: "IS",
    Name: "Iceland",
    CCA3: "ISL",
    Nationality: "Icelander",
  },
  {
    CCA2: "IT",
    Name: "Italy",
    CCA3: "ITA",
    Nationality: "Italian",
  },
  {
    CCA2: "JE",
    Name: "Jersey",
    CCA3: "JEY",
    Nationality: "Channel Islander",
  },
  {
    CCA2: "JM",
    Name: "Jamaica",
    CCA3: "JAM",
    Nationality: "Jamaican",
  },
  {
    CCA2: "JO",
    Name: "Jordan",
    CCA3: "JOR",
    Nationality: "Jordanian",
  },
  {
    CCA2: "JP",
    Name: "Japan",
    CCA3: "JPN",
    Nationality: "Japanese",
  },
  {
    CCA2: "KE",
    Name: "Kenya",
    CCA3: "KEN",
    Nationality: "Kenyan",
  },
  {
    CCA2: "KG",
    Name: "Kyrgyzstan",
    CCA3: "KGZ",
    Nationality: "Kirghiz",
  },
  {
    CCA2: "KH",
    Name: "Cambodia",
    CCA3: "KHM",
    Nationality: "Cambodian",
  },
  {
    CCA2: "KI",
    Name: "Kiribati",
    CCA3: "KIR",
    Nationality: "I-Kiribati",
  },
  {
    CCA2: "KM",
    Name: "Comoros",
    CCA3: "COM",
    Nationality: "Comoran",
  },
  {
    CCA2: "KN",
    Name: "Saint Kitts and Nevis",
    CCA3: "KNA",
    Nationality: "Kittian and Nevisian",
  },
  {
    CCA2: "KP",
    Name: "North Korea",
    CCA3: "PRK",
    Nationality: "North Korean",
  },
  {
    CCA2: "KR",
    Name: "Korea",
    CCA3: "KOR",
    Nationality: "South Korean",
  },
  {
    CCA2: "KW",
    Name: "Kuwait",
    CCA3: "KWT",
    Nationality: "Kuwaiti",
  },
  {
    CCA2: "KY",
    Name: "Cayman Islands",
    CCA3: "CYM",
    Nationality: "Caymanian",
  },
  {
    CCA2: "KZ",
    Name: "Kazakhstan",
    CCA3: "KAZ",
    Nationality: "Kazakhstani",
  },
  {
    CCA2: "LA",
    Name: "Laos",
    CCA3: "LAO",
    Nationality: "Laotian",
  },
  {
    CCA2: "LB",
    Name: "Lebanon",
    CCA3: "LBN",
    Nationality: "Lebanese",
  },
  {
    CCA2: "LC",
    Name: "Saint Lucia",
    CCA3: "LCA",
    Nationality: "Saint Lucian",
  },
  {
    CCA2: "LI",
    Name: "Liechtenstein",
    CCA3: "LIE",
    Nationality: "Liechtensteiner",
  },
  {
    CCA2: "LK",
    Name: "Sri Lanka",
    CCA3: "LKA",
    Nationality: "Sri Lankan",
  },
  {
    CCA2: "LR",
    Name: "Liberia",
    CCA3: "LBR",
    Nationality: "Liberian",
  },
  {
    CCA2: "LS",
    Name: "Lesotho",
    CCA3: "LSO",
    Nationality: "Mosotho",
  },
  {
    CCA2: "LT",
    Name: "Lithuania",
    CCA3: "LTU",
    Nationality: "Lithuanian",
  },
  {
    CCA2: "LU",
    Name: "Luxembourg",
    CCA3: "LUX",
    Nationality: "Luxembourger",
  },
  {
    CCA2: "LV",
    Name: "Latvia",
    CCA3: "LVA",
    Nationality: "Latvian",
  },
  {
    CCA2: "LY",
    Name: "Libya",
    CCA3: "LBY",
    Nationality: "Libyan",
  },
  {
    CCA2: "MA",
    Name: "Morocco",
    CCA3: "MAR",
    Nationality: "Moroccan",
  },
  {
    CCA2: "MC",
    Name: "Monaco",
    CCA3: "MCO",
    Nationality: "Monegasque",
  },
  {
    CCA2: "MD",
    Name: "Moldova",
    CCA3: "MDA",
    Nationality: "Moldovan",
  },
  {
    CCA2: "ME",
    Name: "Montenegro",
    CCA3: "MNE",
    Nationality: "Montenegrin",
  },
  {
    CCA2: "MF",
    Name: "Saint Martin",
    CCA3: "MAF",
    Nationality: "Saint Martin Islander",
  },
  {
    CCA2: "MG",
    Name: "Madagascar",
    CCA3: "MDG",
    Nationality: "Malagasy",
  },
  {
    CCA2: "MH",
    Name: "Marshall Islands",
    CCA3: "MHL",
    Nationality: "Marshallese",
  },
  {
    CCA2: "MI",
    Name: "Midway Islands",
    CCA3: "NULL",
    Nationality: "NULL",
  },
  {
    CCA2: "MK",
    Name: "Macedonia",
    CCA3: "MKD",
    Nationality: "Macedonian",
  },
  {
    CCA2: "ML",
    Name: "Mali",
    CCA3: "MLI",
    Nationality: "Malian",
  },
  {
    CCA2: "MM",
    Name: "Myanmar [Burma]",
    CCA3: "MMR",
    Nationality: "Myanmar",
  },
  {
    CCA2: "MN",
    Name: "Mongolia",
    CCA3: "MNG",
    Nationality: "Mongolian",
  },
  {
    CCA2: "MO",
    Name: "Macau SAR China",
    CCA3: "MAC",
    Nationality: "Chinese",
  },
  {
    CCA2: "MQ",
    Name: "Martinique",
    CCA3: "MTQ",
    Nationality: "French",
  },
  {
    CCA2: "MR",
    Name: "Mauritania",
    CCA3: "MRT",
    Nationality: "Mauritanian",
  },
  {
    CCA2: "MS",
    Name: "Montserrat",
    CCA3: "MSR",
    Nationality: "Montserratian",
  },
  {
    CCA2: "MT",
    Name: "Malta",
    CCA3: "MLT",
    Nationality: "Maltese",
  },
  {
    CCA2: "MU",
    Name: "Mauritius",
    CCA3: "MUS",
    Nationality: "Mauritian",
  },
  {
    CCA2: "MV",
    Name: "Maldives",
    CCA3: "MDV",
    Nationality: "Maldivan",
  },
  {
    CCA2: "MW",
    Name: "Malawi",
    CCA3: "MWI",
    Nationality: "Malawian",
  },
  {
    CCA2: "MX",
    Name: "Mexico",
    CCA3: "MEX",
    Nationality: "Mexican",
  },
  {
    CCA2: "MY",
    Name: "Malaysia",
    CCA3: "MYS",
    Nationality: "Malaysian",
  },
  {
    CCA2: "MZ",
    Name: "Mozambique",
    CCA3: "MOZ",
    Nationality: "Mozambican",
  },
  {
    CCA2: "NA",
    Name: "Namibia",
    CCA3: "NAM",
    Nationality: "Namibian",
  },
  {
    CCA2: "NC",
    Name: "New Caledonia",
    CCA3: "NCL",
    Nationality: "New Caledonian",
  },
  {
    CCA2: "NE",
    Name: "Niger",
    CCA3: "NER",
    Nationality: "Nigerian",
  },
  {
    CCA2: "NF",
    Name: "Norfolk Island",
    CCA3: "NFK",
    Nationality: "Norfolk Islander",
  },
  {
    CCA2: "NG",
    Name: "Nigeria",
    CCA3: "NGA",
    Nationality: "Nigerian",
  },
  {
    CCA2: "NI",
    Name: "Nicaragua",
    CCA3: "NIC",
    Nationality: "Nicaraguan",
  },
  {
    CCA2: "NL",
    Name: "Netherlands",
    CCA3: "NLD",
    Nationality: "Dutch",
  },
  {
    CCA2: "NO",
    Name: "Norway",
    CCA3: "NOR",
    Nationality: "Norwegian",
  },
  {
    CCA2: "NP",
    Name: "Nepal",
    CCA3: "NPL",
    Nationality: "Nepalese",
  },
  {
    CCA2: "NR",
    Name: "Nauru",
    CCA3: "NRU",
    Nationality: "Nauruan",
  },
  {
    CCA2: "NU",
    Name: "Niue",
    CCA3: "NIU",
    Nationality: "Niuean",
  },
  {
    CCA2: "NZ",
    Name: "New Zealand",
    CCA3: "NZL",
    Nationality: "New Zealander",
  },
  {
    CCA2: "OM",
    Name: "Oman",
    CCA3: "OMN",
    Nationality: "Omani",
  },
  {
    CCA2: "PA",
    Name: "Panama",
    CCA3: "PAN",
    Nationality: "Panamanian",
  },
  {
    CCA2: "PE",
    Name: "Peru",
    CCA3: "PER",
    Nationality: "Peruvian",
  },
  {
    CCA2: "PF",
    Name: "French Polynesia",
    CCA3: "PYF",
    Nationality: "French Polynesian",
  },
  {
    CCA2: "PG",
    Name: "Papua New Guinea",
    CCA3: "PNG",
    Nationality: "Papua New Guinean",
  },
  {
    CCA2: "PH",
    Name: "Philippines",
    CCA3: "PHL",
    Nationality: "Filipino",
  },
  {
    CCA2: "PK",
    Name: "Pakistan",
    CCA3: "PAK",
    Nationality: "Pakistani",
  },
  {
    CCA2: "PL",
    Name: "Poland",
    CCA3: "POL",
    Nationality: "Polish",
  },
  {
    CCA2: "PM",
    Name: "Saint Pierre and Miquelon",
    CCA3: "SPM",
    Nationality: "French",
  },
  {
    CCA2: "PN",
    Name: "Pitcairn Islands",
    CCA3: "PCN",
    Nationality: "Pitcairn Islander",
  },
  {
    CCA2: "PR",
    Name: "Puerto Rico",
    CCA3: "PRI",
    Nationality: "Puerto Rican",
  },
  {
    CCA2: "PS",
    Name: "Palestinian Territories",
    CCA3: "PSE",
    Nationality: "Palestinian",
  },
  {
    CCA2: "PT",
    Name: "Portugal",
    CCA3: "PRT",
    Nationality: "Portuguese",
  },
  {
    CCA2: "PW",
    Name: "Palau",
    CCA3: "PLW",
    Nationality: "Palauan",
  },
  {
    CCA2: "PY",
    Name: "Paraguay",
    CCA3: "PRY",
    Nationality: "Paraguayan",
  },
  {
    CCA2: "QA",
    Name: "Qatar",
    CCA3: "QAT",
    Nationality: "Qatari",
  },
  {
    CCA2: "RE",
    Name: "Réunion",
    CCA3: "REU",
    Nationality: "French",
  },
  {
    CCA2: "RO",
    Name: "Romania",
    CCA3: "ROU",
    Nationality: "Romanian",
  },
  {
    CCA2: "RS",
    Name: "Serbia",
    CCA3: "SRB",
    Nationality: "Serbian",
  },
  {
    CCA2: "RU",
    Name: "Russia",
    CCA3: "RUS",
    Nationality: "Russian",
  },
  {
    CCA2: "RW",
    Name: "Rwanda",
    CCA3: "RWA",
    Nationality: "Rwandan",
  },
  {
    CCA2: "SA",
    Name: "Saudi Arabia",
    CCA3: "SAU",
    Nationality: "Saudi Arabian",
  },
  {
    CCA2: "SB",
    Name: "Solomon Islands",
    CCA3: "SLB",
    Nationality: "Solomon Islander",
  },
  {
    CCA2: "SC",
    Name: "Seychelles",
    CCA3: "SYC",
    Nationality: "Seychellois",
  },
  {
    CCA2: "SD",
    Name: "Sudan",
    CCA3: "SDN",
    Nationality: "Sudanese",
  },
  {
    CCA2: "SE",
    Name: "Sweden",
    CCA3: "SWE",
    Nationality: "Swedish",
  },
  {
    CCA2: "SG",
    Name: "Singapore",
    CCA3: "SGP",
    Nationality: "Singaporean",
  },
  {
    CCA2: "SH",
    Name: "Saint Helena",
    CCA3: "SHN",
    Nationality: "Saint Helenian",
  },
  {
    CCA2: "SI",
    Name: "Slovenia",
    CCA3: "SVN",
    Nationality: "Slovene",
  },
  {
    CCA2: "SJ",
    Name: "Svalbard and Jan Mayen",
    CCA3: "SJM",
    Nationality: "Norwegian",
  },
  {
    CCA2: "SK",
    Name: "Slovakia",
    CCA3: "SVK",
    Nationality: "Slovak",
  },
  {
    CCA2: "SL",
    Name: "Sierra Leone",
    CCA3: "SLE",
    Nationality: "Sierra Leonean",
  },
  {
    CCA2: "SM",
    Name: "San Marino",
    CCA3: "SMR",
    Nationality: "Sammarinese",
  },
  {
    CCA2: "SN",
    Name: "Senegal",
    CCA3: "SEN",
    Nationality: "Senegalese",
  },
  {
    CCA2: "SO",
    Name: "Somalia",
    CCA3: "SOM",
    Nationality: "Somali",
  },
  {
    CCA2: "SR",
    Name: "Suriname",
    CCA3: "SUR",
    Nationality: "Surinamer",
  },
  {
    CCA2: "ST",
    Name: "São Tomé and Príncipe",
    CCA3: "STP",
    Nationality: "Sao Tomean",
  },
  {
    CCA2: "SV",
    Name: "El Salvador",
    CCA3: "SLV",
    Nationality: "Salvadoran",
  },
  {
    CCA2: "SY",
    Name: "Syria",
    CCA3: "SYR",
    Nationality: "Syrian",
  },
  {
    CCA2: "SZ",
    Name: "Swaziland",
    CCA3: "SWZ",
    Nationality: "Swazi",
  },
  {
    CCA2: "TC",
    Name: "Turks and Caicos Islands",
    CCA3: "TCA",
    Nationality: "Turks and Caicos Islander",
  },
  {
    CCA2: "TD",
    Name: "Chad",
    CCA3: "TCD",
    Nationality: "Chadian",
  },
  {
    CCA2: "TF",
    Name: "French Southern Territories",
    CCA3: "ATF",
    Nationality: "French",
  },
  {
    CCA2: "TG",
    Name: "Togo",
    CCA3: "TGO",
    Nationality: "Togolese",
  },
  {
    CCA2: "TH",
    Name: "Thailand",
    CCA3: "THA",
    Nationality: "Thai",
  },
  {
    CCA2: "TJ",
    Name: "Tajikistan",
    CCA3: "TJK",
    Nationality: "Tadzhik",
  },
  {
    CCA2: "TK",
    Name: "Tokelau",
    CCA3: "TKL",
    Nationality: "Tokelauan",
  },
  {
    CCA2: "TL",
    Name: "Timor-Leste",
    CCA3: "TLS",
    Nationality: "East Timorese",
  },
  {
    CCA2: "TM",
    Name: "Turkmenistan",
    CCA3: "TKM",
    Nationality: "Turkmen",
  },
  {
    CCA2: "TN",
    Name: "Tunisia",
    CCA3: "TUN",
    Nationality: "Tunisian",
  },
  {
    CCA2: "TO",
    Name: "Tonga",
    CCA3: "TON",
    Nationality: "Tongan",
  },
  {
    CCA2: "TR",
    Name: "Turkey",
    CCA3: "TUR",
    Nationality: "Turkish",
  },
  {
    CCA2: "TT",
    Name: "Trinidad and Tobago",
    CCA3: "TTO",
    Nationality: "Trinidadian",
  },
  {
    CCA2: "TV",
    Name: "Tuvalu",
    CCA3: "TUV",
    Nationality: "Tuvaluan",
  },
  {
    CCA2: "TW",
    Name: "Taiwan",
    CCA3: "TWN",
    Nationality: "Taiwanese",
  },
  {
    CCA2: "TZ",
    Name: "Tanzania",
    CCA3: "TZA",
    Nationality: "Tanzanian",
  },
  {
    CCA2: "UA",
    Name: "Ukraine",
    CCA3: "UKR",
    Nationality: "Ukrainian",
  },
  {
    CCA2: "UG",
    Name: "Uganda",
    CCA3: "UGA",
    Nationality: "Ugandan",
  },
  {
    CCA2: "US",
    Name: "USA",
    CCA3: "USA",
    Nationality: "American",
  },
  {
    CCA2: "UY",
    Name: "Uruguay",
    CCA3: "URY",
    Nationality: "Uruguayan",
  },
  {
    CCA2: "UZ",
    Name: "Uzbekistan",
    CCA3: "UZB",
    Nationality: "Uzbekistani",
  },
  {
    CCA2: "VA",
    Name: "Vatican City",
    CCA3: "VAT",
    Nationality: "Italian",
  },
  {
    CCA2: "VC",
    Name: "Saint Vincent and the Grenadines",
    CCA3: "VCT",
    Nationality: "Saint Vincentian",
  },
  {
    CCA2: "VE",
    Name: "Venezuela",
    CCA3: "VEN",
    Nationality: "Venezuelan",
  },
  {
    CCA2: "VI",
    Name: "U.S. Virgin Islands",
    CCA3: "VIR",
    Nationality: "Virgin Islander",
  },
  {
    CCA2: "VN",
    Name: "Vietnam",
    CCA3: "VNM",
    Nationality: "Vietnamese",
  },
  {
    CCA2: "VU",
    Name: "Vanuatu",
    CCA3: "VUT",
    Nationality: "Ni-Vanuatu",
  },
  {
    CCA2: "WF",
    Name: "Wallis and Futuna",
    CCA3: "WLF",
    Nationality: "Wallis and Futuna Islander",
  },
  {
    CCA2: "WS",
    Name: "Samoa",
    CCA3: "WSM",
    Nationality: "Samoan",
  },
  {
    CCA2: "YE",
    Name: "Yemen",
    CCA3: "YEM",
    Nationality: "Yemeni",
  },
  {
    CCA2: "YT",
    Name: "Mayotte",
    CCA3: "MYT",
    Nationality: "French",
  },
  {
    CCA2: "ZA",
    Name: "South Africa",
    CCA3: "ZAF",
    Nationality: "South African",
  },
  {
    CCA2: "ZM",
    Name: "Zambia",
    CCA3: "ZMB",
    Nationality: "Zambian",
  },
  {
    CCA2: "ZW",
    Name: "Zimbabwe",
    CCA3: "ZWE",
    Nationality: "Zimbabwean",
  },
];

export function findCountryCodeByNationality(nationality) {
  for (let i = 0; i < countryCodesAndNames.length; i++) {
    if (countryCodesAndNames[i].Nationality == nationality) {
      return countryCodesAndNames[i].CCA2;
    }
  }
}

export function findCountryNameByNationality(nationality) {
  for (let i = 0; i < countryCodesAndNames.length; i++) {
    if (countryCodesAndNames[i].Nationality == nationality) {
      return countryCodesAndNames[i].Name;
    }
  }
}

export function findCountryCodeByCountryName(countryName) {
  for (let i = 0; i < countryCodesAndNames.length; i++) {
    if (countryCodesAndNames[i].Name == countryName) {
      return countryCodesAndNames[i].CCA2;
    }
  }
}
